### ISSUE TITLE
卡巴斯基报毒

### ISSUE THREAD

**Issue by XianWeiGP-R** [LightQuanta/BiliResourceDownloader#1]
V1.1.0的biliresourcedownloader_1.1.0_x64-setup.exe在卡巴斯基报毒，请修复一下。

**Comment by LightQuanta** [comment]
这个真没法整，[tauri官方](https://github.com/tauri-apps/tauri/issues/2486)都没解决这个问题，整微软的签名证书还要钱

我只能说代码都放这了，release里的也是GitHub Action编译出的，实在信不过可以本地编译
